name: "SonarCloud C++ Analysis (The Official Way)"

on:
  workflow_dispatch:

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
    # 步骤1: 检出你指定的旧代码
    - name: Checkout target source code
      uses: actions/checkout@v4
      with:
        ref: '50eed9b008e7eff012e788a8a328901f68373579'
        fetch-depth: 0

    # ========================== 最终核心修改点 ==========================
    # 步骤2: (新) 使用官方的SonarCloud Action，它会处理所有事情
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        # 在这里定义我们的构建命令，Action会自动用build-wrapper包裹它
        build-sh: |
          # 1. 安装依赖
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libssl-dev protobuf-compiler libgflags-dev libleveldb-dev libprotobuf-dev libprotoc-dev
          
          # 2. 运行编译
          cmake .
          make -j2
        
        # 传入sonar-scanner需要的参数
        args: >
          -Dsonar.organization=zhang-weibing
          -Dsonar.projectKey=zhang-weibing_brpc
    # ====================================================================
